# Generated by Django 3.2 on 2022-12-16 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 26, 25, 87517), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 26, 25, 87517), editable=False),
        ),
    ]
