# Generated by Django 3.2 on 2022-12-19 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 2, 179625), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.IntegerField(default=10, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 33, 2, 179625), editable=False),
        ),
    ]
