# Generated by Django 3.2 on 2022-12-19 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20221219_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(default=11111111111111, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 46, 4, 32038), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 46, 4, 32038), editable=False),
        ),
    ]
