# Generated by Django 3.2 on 2022-12-16 15:45

import card.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20221216_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(choices=[('1', '1 year'), ('2', '6 months'), ('3', '30 days')], default=card.models.default_expiration_date),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 45, 22, 503299), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 16, 45, 22, 503299), editable=False),
        ),
    ]
