# Generated by Django 3.2 on 2022-12-19 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20221219_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(default=10000000000000, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 47, 49, 94934), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 12, 47, 49, 94934), editable=False),
        ),
    ]
