# Generated by Django 3.2 on 2022-12-19 15:42

import card.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20221219_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(choices=[('<function year_expiration_date at 0x000001CA02B28DC0>', '1 year'), ('<function halfyear_expiration_date at 0x000001CA02B28F70>', '6 months'), ('<function default_expiration_date at 0x000001CA02B28040>', '30 days')], default=card.models.default_expiration_date, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 16, 42, 2, 967989), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 16, 42, 2, 967989), editable=False),
        ),
    ]
