# Generated by Django 3.2 on 2022-12-19 15:42

import card.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20221219_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(choices=[('2023-12-19 16:42:36.691882', '1 year'), ('<function halfyear_expiration_date at 0x00000210F83650D0>', '6 months'), ('<function default_expiration_date at 0x00000210F8365040>', '30 days')], default=card.models.default_expiration_date, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 16, 42, 36, 692883), editable=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='usage_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 16, 42, 36, 692883), editable=False),
        ),
    ]
